name: "Docker Cloudron"
description: "Greet someone and record the time"
branding:
  icon: "upload-cloud"
  color: "blue"
author: "Ross MacLean"
inputs:
  docker-user:
    description: "Docker user to use when uploading container"
    required: true
  app-name:
    description: "Application name for Dockerhub"
    required: true
  cloudron-server:
    description: "FQDN of Cloudron server e.g. my.server.com"
    required: true
  app-domain:
    description: "Domain under which the app will be install in Cloudron .e.g. myapp.server.com"
    required: true
  dockerhub-token:
    description: "Dockerhub token"
    required: true
  cloudron-token:
    description: "Cloudron token"
    required: true
  version:
    description: "App version"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Print version
      run: echo "Version ${GITHUB_SHA::7}"
      shell: bash
    - name: Docker login
      run: docker login --username ${{ inputs.docker-user }} --password ${{ inputs.dockerhub-token }}
      shell: bash
    - name: Docker build
      run: docker build -t ${{ inputs.docker-user }}/${{ inputs.app-name }}:${{ inputs.version }} -t ${{ inputs.docker-user }}/${{ inputs.project-name }}:latest .
      shell: bash