name: "Docker Build Push"
description: "Build and push Docker image"
branding:
  icon: "upload-cloud"
  color: "blue"
author: "Ross MacLean"
inputs:
  docker-user:
    description: "Docker user to use when uploading container"
    required: true
  image-name:
    description: "Image name"
    required: true
  dockerhub-token:
    description: "Dockerhub token"
    required: true
  version:
    description: "App version"
    required: true
runs:
  using: composite
  steps:
    - name: Print version
      run: echo "Version ${{ inputs.version }}"
      shell: bash
    - name: Docker login
      run: docker login --username ${{ inputs.docker-user }} --password ${{ inputs.dockerhub-token }}
      shell: bash
    - name: Docker build
      run: docker build -t ${{ inputs.docker-user }}/${{ inputs.image-name }}:${{ inputs.version }} -t ${{ inputs.docker-user }}/${{ inputs.image-name }}:latest .
      shell: bash
    - name: Docker push
      run: docker push --all-tags ${{ inputs.docker-user }}/${{ inputs.image-name }}
      shell: bash
